#### Override this file by adding a setting-custom.yaml in the root folder (next to settings.yaml file)
#### Prefix is used to customize the elements, eg dgt41 will produce: dgt41-alert, dgt41-modal, etc
#### Comment out the elements you don't want to be created
'prefix': 'dgt41'
'elements':
            - 'alert'
            - 'button'
            - 'carousel'
            - 'collapse'
            - 'dropdown'
            - 'modal'
            - 'popover'
            - 'scrollspy'
            - 'tabs'
            - 'tooltip'
            
